export const PRISMA_CLIENT_ERRORS_CODE = {
  'P2000': 'The provided value is too long for the column type in the database',
  'P2001': 'No record was found for the specified query',
  'P2002': 'Unique constraint violation: A record with this value already exists',
  'P2003': 'Foreign key constraint violation: Invalid reference to a related record',
  'P2004': 'A constraint violation occurred for a specific field in the database',
  'P2005': 'Invalid value provided for the database column type',
  'P2006': 'The provided value for the field is invalid',
  'P2007': 'The data in the database is inconsistent with the Prisma schema constraints',
  'P2008': 'Failed to validate the Prisma query. Please check your query structure',
  'P2009': 'Invalid input for the Prisma operation. Ensure the data matches the schema',
  'P2010': 'Error interpreting the database response',
  'P2011': 'Required constraint failed for one or more fields',
  'P2012': 'Missing a required field in the input data for the operation',
  'P2013': 'Missing required arguments for the Prisma query',
  'P2014': 'Incomplete relationship: Related records are missing',
  'P2015': 'Expected related records were not found',
  'P2016': 'The query returned null but it was expected to return data',
  'P2017': 'Unexpected database modification detected. Check for schema changes',
  'P2018': 'The database connection was lost during the operation',
  'P2019': 'The database structure does not match the Prisma schema',
  'P2020': 'The provided value is out of range for the expected input',
  'P2021': 'The requested Prisma model was not found in the schema',
  'P2022': 'The column referenced in the operation does not exist in the database',
  'P2023': 'Invalid response received from the database during the query',
  'P2024': 'The operation timed out due to taking too long',
  'P2025': 'The record to delete or update was not found',
} as const